drift_blog/urls.py
"""from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
]
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    #path('', include('pages.urls')),
    path('posts/', include('posts.urls')),
    path('orders/', include('orders.urls')),
    path('tournaments/', include('tournaments.urls')),
    path('admin/', admin.site.urls, name='admin_page'),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.PostListView.as_view(), name='posts_list'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('new/', views.PostCreateView.as_view(), name='post_new'),
    path('<int:pk>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
]

tournaments/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils import timezone

# Create your models here.
class Tournament(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255, verbose_name="Название")
    url = models.CharField(max_length=255, verbose_name="Адрес", default="123321")
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания') #default=timezone.now
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name = "Создал"
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tournament_detail', args=[str(self.id)])

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}" type="text/css">

    <title>{% block title %}Главная страница Drift{% endblock title %}</title>

  </head>
  <body>
    <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark mb-4" style="height: 100px;">
      <a class="navbar-brand" href="{% url 'home' %}">Главная страница</a>
      <a class="navbar-brand" href="{% url 'posts_list' %}">Новости</a>

      {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'order_new' %}">Оставить заявку на участие</a>
        <a class="navbar-brand" href="{% url 'pilots_list' %}">Пилоты</a>
        <a class="navbar-brand" href="{% url 'tournament_list' %}">Турниры</a>
      {% endif %}
      <a class="navbar-brand" href="#">Календарь мероприятий</a>
      <a class="navbar-brand" href="#">Технический регламент автомобилей</a>

      {% if user.is_superuser %}
      <a class="navbar-brand" href="{% url 'tournament_new' %}">Создать турнир</a>

        <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a href="{% url 'post_new' %}">+ Создать новость</a></li>
        </ul>
      {% else %}
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a href="{% url 'signup' %}">Регистрация нового пользователя</a>
            </li>
        </ul>
      {% endif %}

      <button class="navbar-toggler" type="button" data-toggle="collapse"\
      data-target="#navbarCollapse" aria-controls="navbarCollapse"\
      aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        {% if user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link dropdown-toggle" href="#" id="userMenu"\
              data-toggle="dropdown" aria-haspopup="true" aria-expanded\
              ="false">
                {{ user.username }}
              </a>
              <div class="dropdown-menu dropdown-menu-right"\
              aria-labelledby="userMenu">
                <a class="dropdown-item" href="{% url 'password_change' %}">Изменить пароль</a>
                <div class="dropdown-divider"></div>
                {% if user.is_superuser %}
                  <a class="dropdown-item" href="/admin">Админ-панель</a>
                  <div class="dropdown-divider"></div>
                {% endif %}
                {% if user.is_authenticated %}
                  <a class="dropdown-item" href="{% url 'orders_list' %}">Заявки</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'user_profile' %}">Личный кабинет</a>
                {% endif %}
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">Выйти</a>
              </div>
            </li>
          </ul>
        {% else %}
          <form class="form-inline ml-auto">
            <a href="{% url 'login' %}" class="btn btn-outline-secondary">Войти</a>
          </form>
        {% endif %}
      </div>

      {% if user.is_authenticated %}
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Ваш запрос" aria-label="Поиск">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
        </form>
      {% endif %}


    </nav>

<!--    <div class="container"> -->
    <div class="container" style="top: 110px; bottom: 120px; margin-bottom: 100px; position: relative;">
      {% block content %}
      {% endblock content %}
    </div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"\ integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4\
    YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/\
    JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  </body>

<!--
  <footer class="blog-footer fixed-bottom" style="height: 96px; width: 100%; left: 0px; right: 0px; text-align: center; color: white; background-color: #343a40!important; margin-top: 100px;">
-->

<!--  <p style="margin-top: 10px;">Форма обратной связи <a href="#">BMSTU</a>.</p>
  <div class="footer-copyright text-center py-3" style="width: 100%;">© 2019 Copyright:
    <a href="{% url 'feedback_form' %}"> Обратная связь</a>
  </div>

  <div class="soc-icons">
    <ul>
      <li><a href="https://github.com/arthanadftz" target="_blank"><i class="fa fa-github fa-2x"></i></a></li>
      <li><a href="https://vk.com/" target="_blank"><i class="fa fa-vk fa-2x"></i></a></li>
      <li><a href="https://youtube.com/" target="_blank"><i class="fa fa-youtube-square fa-2x"></i></a></li>
      <li><a href="https://github.com/arthanadftz" target="_blank"><i class="fa fa-telegram fa-2x"></i></a></li>
    </ul>
  </div>
  <div class="footer-copyright text-center py-3" style="width: 100%;">© 2019 Copyright:

  </div>
</footer>

<footer class="page-footer font-small special-color-dark pt-4" style="position: fixed; width: 100%; bottom: 0px; left: 0px;">
-->

  <footer class="page-footer fixed-bottom special-color-dark pt-4" style="height: 110px; width: 100%; left: 0px; right: 0px; margin-top: 100px;">
    <div class="container">
      <ul class="list-unstyled list-inline text-center">
        <li class="list-inline-item">
          <a class="btn-floating btn-fb mx-1" href="https://youtube.com/">
        <!--    <i class="fab fa-youtube"> </i> -->
            <i class="fa fa-youtube-square fa-1x"></i>
          </a>
        </li>
      <!--  <li class="list-inline-item">
          <a class="btn-floating btn-gplus mx-1" href="https://google.com/">
            <i class="fab fa-google-plus-g"> </i>
          </a>
        </li> -->
        <li class="list-inline-item">
          <a class="btn-floating btn-li mx-1" href="https://vk.com/">
    <!--        <i class="fab fa-vk"> </i> -->
            <i class="fa fa-vk fa-1x"></i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-li mx-1" href="https://github.com/Arthadftz/">
    <!--        <i class="fab fa-github"> </i> -->
            <i class="fa fa-github fa-1x"></i>
          </a>
        </li>
      </ul>

    <div class="footer-copyright text-center py-3" style="width: 100%;">© 2019 Copyright:
      <a href="{% url 'feedback_form' %}"> Обратная связь</a>
    </div>

  </footer>
</html>

templates/feedback.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Форма обратной связи{% endblock %}

{% block content %}
  <h1>Форма обратной связи</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success ml-2" type="submit">Отправить</button>
    <a class="btn btn-light ml-2" href="{% url 'home' %}">Вернуться</a>
  </form>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block title %}Глвная страница{% endblock %}

{% block content %}
  <div class="jumbotron">
    <h1 class="display-4">Главная страница проекта</h1>
    <p class="lead">Проект Drift.</p>
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="{% url 'posts_list' %}" role="button">Новости</a>
    </p>
  </div>
{% endblock %}

templates/order_detail.html
{% extends 'base.html' %}

{% block title %}Заявки пользователя{% endblock %}

{% block content %}
  <div class="content-section">
      <div class="media-body">
        <h2 class="account-heading">{{ object.title }}</h2>
        <p class="text-body">Пилот: {{ object.author.full_name }}</p>
        <p class="text-body">Дата заявки: {{ object.date }} </p>
        <p class="text-body">Автомобиль: {{ object.car.car_name }} {{ object.car.car_model }}</p>
        <p class="text-body">Двигатель: {{object.car.car_engine}}</p>
        <p class="text-body">Мощность: {{object.car.car_power}} л.с.</p>
          <p class="text-body">Покрышки: {{ object.car.car_tyres }}</p>
        {% if object.status == 'ГТВ' %}
          <p class="text-body btn btn-success m-3">Статус: {{ object.status }}</p>
        {% else %}
          <p class="text-body btn btn-warning m-3">Статус: {{ object.status }}</p>
        <!-- <p class="list-group-item-warning">Статус: {{ object.status }}</p> -->
        {% endif %}
      </div>
      <br>
      {% if user.is_authenticated %}
        <p>
          <a class="btn btn-primary ml-2" href="{% url 'order_edit' object.pk %}">Изменить данные</a>
        </p>
      {% endif %}
      <p><a class="btn btn-secondary ml-2" href="{% url 'home' %}">Вернуться на главную страницу</a></p>
  </div>
{% endblock content %}

templates/order_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <h1>Подать заявку на участие в чемпионате</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success ml-2" type="submit">Создать</button>
    <a class="btn btn-light ml-2" href="{% url 'home' %}">Вернуться</a>
  </form>
{% endblock %}

templates/orders_list.html
{% extends 'base.html' %}

{% block title %}Заявки{% endblock %}

{% block content %}
  {% for order in object_list %}
    <div class="card" style="background: #f8f9fa; border: 1px solid black; border-radius: 20px;">
      <div class="card-header">
        <span class="font-weight-bold">{{ order.title }}</span> &middot;

      </div>
      <div class="card-body">
        <span class="text-muted">Создал: {{ order.author }}</span>
        <span class="text-muted">Дата создания: {{ order.date }}</span>
        {% if order.status == 'ГТВ' %}
          <p class="text-body btn btn-success m-3">{{ order.status }}</p>
        {% else %}
          <p class="btn btn-warning m-3">{{ order.status }}</p>
        {% endif %}
        <p class="text-body">Автомобиль: {{ order.car }} </p>
      </div>
      <a class="btn btn-secondary m-3" href="{% url 'order_detail' order.pk %}">Просмотр</a>
    </div>
    <br />
  {% endfor %}
{% endblock %}

templates/pilots_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Список пилотов чемпионата{% endblock %}

{% block content %}
  <h2 style="background: #f8f9fa; border: 1px solid grey; border-radius: 10px; position: center; text-align: center">Список пилотов чемпионата</h2>
  <ul class="list-group">
    {% for pilot in pilots %}
      <li class="list-group-item disabled">{{ pilot.full_name }} | {{ pilot.date_of_birth }} | Команда {{ order.car.car_tyres }} Tyres | Машина {{ order.car.car_name }} {{ order.car.car_model }} | Двигатель : {{ order.car.car_engine }} - {{ order.car.car_power }} л.с.</li>
    {% endfor %}
  </ul>
{% endblock %}

templates/post_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Удалить новость</h1>
  <form action="" method="POST">
    {% csrf_token %}
    <p>Вы уверены, что хотите удалить "{{ post.title }}"?</p>
    <button class="btn btn-success ml-2" type="submit">Подтвердить</button>
    <a class="btn btn-danger ml-2" href="{% url 'posts_list' %}">Вернуться</a>
</form>
{% endblock %}

templates/post_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="content-section">
      <div class="media">
        {% if post.document %}
          <img src="{{ post.document.url }}" class="image-responsive" style="height: 600px; width: 800px; margin-left: 130px; margin-right: 20px; margin-bottom: 16px; border: 1px solid black; border-radius: 20px;">
          <br>
        {% endif %}
      </div>

      <div class="media-body">
        <h2 class="account-heading">{{ object.title }}</h2>
        <p class="text-body">by {{ object.author }} | {{ object.date }}</p>
        <p class="text-body">{{ object.body }}</p>
      </div>

      {% if user.is_superuser %}
        <p>
          <a class="btn btn-primary ml-2" href="{% url 'post_edit' post.pk %}">Изменить</a>
          <a class="btn btn-warning ml-2" href="{% url 'post_delete' post.pk %}">Удалить</a>
        </p>
      {% endif %}
      <br>
      <p><a class="btn btn-secondary ml-2" href="{% url 'posts_list' %}">Вернуться к списку новостей</a></p>
  </div>
{% endblock content %}

<!--
<div class="post-entry" style="border: 1px solid black; border-radius: 15px; background: white;">
  <h2>{{ object.title }}</h2>
  <p>by {{ object.author }} | {{ object.date }}</p>
  <p>{{ object.body }}</p>
  {% if post.document %}
    <img src="{{ post.document.url }}" class="image-responsive" style="height: 200px; width: 250px;">
  {% endif %}
</div>
-->

templates/post_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <h1>Создать новость</h1>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success ml-2" type="submit">Сохранить</button>
    <a class="btn btn-light ml-2" href="{% url 'home' %}">Вернуться</a>
  </form>
{% endblock %}

templates/posts_list.html
{% extends 'base.html' %}

{% block title %}Новости{% endblock %}

{% block content %}
  {% for post in object_list %}
    <div class="card" style="background: #f8f9fa; border: 1px solid black; border-radius: 20px;">
      <div class="card-header">
        <span class="font-weight-bold">{{ post.title }}</span> &middot;
        <span class="text-muted">Опубликовал {{ post.author }} | {{ post.date }}</span>
      </div>
      <div class="card-body">
        {{ post.body }}
        {% if post.document %}
          <img src="{{ post.document.url }}" class="image-responsive" style="border: 1px solid black; border-radius: 20px;">
        {% endif %}
      </div>
      <a class="btn btn-secondary m-3" href="{% url 'post_detail' post.pk %}">Подробнее</a>
    </div>
    <br />
  {% endfor %}
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Регистрация нового пользователя{% endblock %}

{% block content %}
  <h2>Регистрация нового пользователя</h2>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success ml-2" type="submit">Зарегистрироваться</button>
    <a class="btn btn-danger ml-2" href="{% url 'home' %}">Вернуться</a>
  </form>
{% endblock %}

templates/tournament_detail.html
{% extends 'base.html' %}

{% block title %}Турнир{% endblock %}

{% block content %}
  <div class="content-section">
      <div class="media-body">
        <h2 class="account-heading">{{ object.name }}</h2>
        <p class="text-body">Создан: {{ object.date }} </p>
        <p class="text-body">Создал: {{ object.author.full_name }}</p>
      </div>
      <br>
      {% if user.is_authenticated %}
        <p>
          <a class="btn btn-primary ml-2" href="https://challonge.com/ru/{{ object.url }}" target="_blank">Турнирная сетка</a>
          <p><a class="btn btn-secondary ml-2" href="{% url 'order_new' %}">Подать заявку на участие</a></p>
        </p>
      {% endif %}
      <p><a class="btn btn-secondary ml-2" href="{% url 'tournament_list' %}">Вернуться к списку турниров</a></p>
  </div>
{% endblock content %}

templates/user_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Личный кабинет пользователя - {{ user.username }}{% endblock %}

{% block content %}
  <div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{ user.userprofile.avatar.url }}" alt="">
      <div class="media-body">
        <h2 class="account-heading">Имя пользователя: {{ user.username }}</h2>
        <p class="text-body">ФИО: {{ user.full_name }}</p>
        <p class="text-body">Дата рождения: {{ user.date_of_birth }}</p>
        <p class="text-body">Контактный телефон: {{ user.phone_no }}</p>
        <p class="text-body">Email: {{ user.email }}</p>
        <p class="text-body">Роль пользователя: {{ user.user_role }}</p>
      </div>
    </div>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4"></legend>
          {{ u_form|crispy }}
          {{ p_form|crispy }}
      </fieldset>
      <div class="form-group">
        <button class="btn btn-success ml-2" type="submit">Изменить данные</button>
      </div>
    </form>

{% endblock %}


<!--
  <div class="card" style="width: 50rem; background-color: #87CEFA">
    <img src="{{ user.userprofile.avatar.url }}" class="card-img-top" alt="" style="width: 300px; height: 300px; display: block; margin-left: auto; margin-right: auto">
    <div class="card-body">
      <h5 class="card-title">Имя пользователя: {{ user.username }}</h5>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">ФИО: {{ user.full_name }}</li>
        <li class="list-group-item">Дата рождения: {{ user.date_of_birth }}</li>
        <li class="list-group-item">Контактный телефон: {{ user.phone_no }}</li>
        <li class="list-group-item">Email: {{ user.email }}</li>
        <li class="list-group-item">Роль пользователя: {{ user.user_role }}</li>
        {% if user.user_role == 'СТ' %}
          <li class="list-group-item">Группа: {{ user.student_group }}</li>
        {% endif %}
    </ul>
  </div>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ u_form|crispy }}
    {{ p_form|crispy }}
    <button class="btn btn-success ml-2" type="submit">Изменить данные</button>
    <button class="btn btn-outline-info" type="submit">Update</button>
  </form>
</div>
-->